### ISSUE TITLE
Moodle Operator does not handle creation new Moodle instances in parallel

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus-operators#36]
Moodle Operator thread that is tracking progress of one Moodle instance blocks other create actions to be processed.

**Comment by danielpygo** [comment]
I was not able to validate this with identical moodle instances, with different names only (moodle1, moodle2). 

Could you try again? 
They both seem to be progressing, with moodle1 still advancing and finishing before moodle2 did. It does seem to be in parallel

**Comment by devdattakulkarni** [comment]
Oh okay
